### PR TITLE
update broccoli-favicon and support embroider

### PR DESCRIPTION
**Pull request by miguelcobain**
@Exelord This PR updates the broccoli-favicon package and the overall ember-cli project (via ember-cli-update).
Both things are in separate commits.

This PR also includes #96 .

### CODE REVIEW

**Comment by miguelcobain** [comment]
@davewasmer @Exelord looks like all tests are green! 💚

**Comment by miguelcobain** [comment]
@davewasmer @Exelord friendly reminder for this PR. I'm available for any kind of assistance. :+1:

**Comment by Exelord** [comment]
Ok, I think we are all good :) Thank you for taking care of it!

**Comment by miguelcobain** [comment]
@Exelord thank you for merging!
Now, onwards to the release! :D

**Pull request merged**
