### PR TITLE
keep local files

### PR DESCRIPTION
**Pull request by jlami**
To be able to specify a special custom favicon-16x16.png with better contrast

### CODE REVIEW

**Comment by davewasmer** [comment]
Mind adding a test for this @jlami?

**Comment by jlami** [comment]
I don't really know how to write a test that checks for presence of files after a build, otherwise I would certainly do it ;)

**Comment by jlami** [comment]
Tried my hand at the test.

I did have to change the travis setup, since the update to ember 2.15 removed the `npm test` and only did the default ember-cli tests. If we also want those test we will have to change the travis setup in some way to have multiple build stages or find some other way to include `npm test` as a single entry to the build matrix. I don't really know if this could work:
```
matrix:
  include:
    script: npm test
```

**Comment by Exelord** [comment]
Its already on master :) Fixed!

**Comment by jlami** [comment]
Great!

But I dont know whether https://github.com/davewasmer/ember-cli-favicon/blob/master/test.js is really being called at this point?
https://travis-ci.org/davewasmer/ember-cli-favicon/jobs/388042007#L775 only shows the basic dummy tests as far as I can tell.

**Comment by Exelord** [comment]
I fixed that in #67 (tests are running there correctly) And the feature is already there and working :)

**Comment by jlami** [comment]
Yes, my PR here (67) did have a fix for running `npm test`. But on master the tests are not running. Isn't it a good idea to have the actual test run there too?

**Comment by Exelord** [comment]
Sure and they are already fixed in #67 as I mentioned. But it doesn't matter as tests are passing locally and the feature is tested :)

**Comment by jlami** [comment]
But isn't it good practice to keep the tests in the master branch, so future changes will also test it again?

**Comment by Exelord** [comment]
This PR is meant to be merged.

**Comment by jlami** [comment]
Ok, but it's now closed without being merged. Just wanted to make sure.

**Pull request closed without merging**
