### PR TITLE
[Breaking] Drop support for Ember < 3.16, Node 6+8

### PR DESCRIPTION
**Pull request by simonihmig**
Using `ember-cli-update` to update dependencies and drop support for old versions.

### CODE REVIEW

**Comment by simonihmig** [comment]
Seems Travis is not enabled by default anymore for OSS projects. Added a commit that sets up Github Actions. Although that will only get triggered once the config is in `master`!

**Comment by simonihmig** [comment]
Hey @davewasmer, could you have a look at this (and #96) please?

**Comment by davewasmer** [comment]
@simonihmig Unfortunately I'm no longer supporting any production Ember apps at the moment, so I'm not comfortable doing the code review / planning / maintenance here. I know @Exelord had taken over much of the work on this addon - perhaps they could chime in?

**Review by Exelord — APPROVED** [review]
Looks good to me :) Though, before a release the new CI setup needs to be verified.

**Comment by simonihmig** [comment]
@Exelord seems you got into trouble with the Guthub actions config, sorry about that!

The config I used worked nicely when used with `yarn`. I quickly changed `yarn` to `npm`, but apparently missed changing to `npm run`, which you then fixed. Other than that it seems it is the same error that does not go away, even with your many changes afterwards: `Cannot find module 'internal/util/types'`. Looking at https://github.com/remy/nodemon/issues/1124, it seems it is related to having an old version of `npm`, which indeed in CI is [v3.5.4](https://github.com/davewasmer/ember-cli-favicon/runs/2114965928?check_suite_focus=true#step:7:10). Any idea why it is that old?

Other than that, we could switch to `yarn` maybe?

**Comment by Exelord** [comment]
yeah 😅  was trying to solve it but I failed at the end. The weird thing is, only the ember-try tests fail. It might be related to npm, thanks for pointing this out! I will try to upgrade it, otherwise will fallback to yarn (though I would like to stick to native)

**Comment by Exelord** [comment]
Screen Shot 2021-03-17 at 18 20 47
It looks like somehow ember-try is using wrong npm version, though the latest is installed 🤔

**Pull request merged**
